# Generated by Django 4.0.5 on 2022-07-25 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('especie', models.CharField(choices=[('1', 'Perro'), ('2', 'Gato')], default='Elegir Opcion', max_length=20)),
                ('sexo', models.CharField(choices=[('1', 'Macho'), ('2', 'Hembra')], default='Elegir Opcion', max_length=20)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('tamanio', models.CharField(choices=[('1', 'Grande'), ('2', 'Mediano'), ('3', 'Chico')], default='Elegir Opcion', max_length=20)),
                ('vacunas_aplicadas', models.PositiveIntegerField(blank=True, null=True)),
                ('castracion', models.CharField(choices=[('1', 'Si'), ('2', 'No')], default='Elegir Opcion', max_length=20)),
                ('desparasitado', models.CharField(choices=[('1', 'Si'), ('2', 'No')], default='Elegir Opcion', max_length=20)),
                ('discapacidad', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='posteos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posteos', to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../media/user.png', upload_to='profile_pics')),
                ('dni', models.PositiveIntegerField(null=True)),
                ('sexo', models.CharField(choices=[('1', 'Masculino'), ('2', 'Femenino'), ('3', 'Prefiero no decirlo')], max_length=30)),
                ('edad', models.PositiveIntegerField(null=True)),
                ('telefono', models.PositiveIntegerField(null=True)),
                ('localidad', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=30)),
                ('ocupacion', models.CharField(max_length=50)),
                ('carga_horaria', models.PositiveIntegerField(null=True)),
                ('dias_homeoffice', models.PositiveIntegerField(null=True)),
                ('cantidad_hijos', models.PositiveIntegerField(null=True)),
                ('cantidad_mascotas', models.PositiveIntegerField(null=True)),
                ('especie_mascota', models.CharField(max_length=50)),
                ('espacio_abierto', models.CharField(choices=[('1', 'Patio o Parque'), ('2', 'Terraza o Balcon'), ('3', 'No poseo')], max_length=40)),
                ('ig', models.URLField(null=True)),
                ('fb', models.URLField(null=True)),
                ('tw', models.URLField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_posteos', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pinderApp.postcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinderApp.post')),
            ],
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['from_user', 'to_user'], name='pinderApp_r_from_us_b1bf5d_idx'),
        ),
    ]
